### ISSUE TITLE
Create Detection Object/Format

### ISSUE THREAD

**Issue by jpatton-USGS** [usgs/earthquake-detection-formats#1]
Create a detection object/format that contains the following:
- Latitude
- Longitude
- Time 
- Depth

**Comment by jpatton-USGS** [comment]
Call it a hypocenter?

**Comment by jpatton-USGS** [comment]
Add Optional:
- LatitudeError
- LongitudeError
- TimeError 
- DepthError

**Comment by jpatton-USGS** [comment]
Name it "Hypo"

**Comment by jmfee-usgs** [comment]
I suggest not abbreviating...
